scality/Arsenal

- index.js
- lib/policyEvaluator/evaluator.js
- lib/policyEvaluator/utils/checkArnMatch.js
- lib/policyEvaluator/utils/conditions.js
- lib/policyEvaluator/utils/variables.js
- lib/policyEvaluator/utils/wildcards.js
- package.json
- tests/unit/policyEvaluator.js
- tests/utils/samplePolicies.json
Implements and tests a user policy evaluator.  Can be extended to handle resource policies.
> Implement policy evaluator

- errors/arsenalErrors.json
- index.js
- lib/policy/policyValidator.js
- lib/policy/userPolicySchema.json
- package.json
- tests/unit/policy/test_policyValidator.js
Validates user policies against the JSON schema per AWS' documentation
and validator implementation.
> FT: User Policy validator

- tests/unit/stringHash.js
- Increase timeout to remove flaky test from
public Circle CI
Fixes https://github.com/scality/Arsenal/issues/93
> [Tests](fix): Fix flaky test timeout rel/1.1

- lib/policy/userPolicySchema.json
- tests/unit/policy/test_policyValidator.js
> BF: Restrict policy top level properties

- README.md
- circle.yml
- index.js
- lib/Clustering.js
- package.json
- tests/functional/clustering/clustering.js
- tests/functional/clustering/utils/killed.js
- tests/functional/clustering/utils/shutdownTimeout.js
- tests/functional/clustering/utils/simple.js
- tests/functional/clustering/utils/watchdog.js
- Add a clustering, simple to use, with an internal
watchdog
> [Clustering](ft): Add clustering

- lib/policyEvaluator/RequestContext.js
- lib/policyEvaluator/utils/conditions.js
- package.json
- tests/unit/policyEvaluator.js
> Handles mapped ipv4 request ip addresses.

- tests/functional/clustering/utils/killed.js
- tests/functional/clustering/utils/shutdownTimeout.js
- tests/functional/clustering/utils/simple.js
- tests/functional/clustering/utils/watchdog.js
- tests/unit/algos/list/MPU.js
- tests/unit/algos/list/basic.js
- tests/unit/algos/list/delimiter.js
http://ci.ironmann.io/gh/scality/Integration/2367#build-parameters End to end passed without any problem.
> refactor(werelogs): use new API

- lib/errors.js
- tests/unit/errors.js
- Allow custom descriptions in arsenal errors
Fixes https://github.com/scality/Arsenal/issues/117
> [Errors](ft): Allowing custom descriptions

- lib/auth/v2/constructStringToSign.js
- lib/auth/v4/createCanonicalRequest.js
- tests/unit/auth/v2/constructStringToSign.js
- tests/unit/auth/v4/createCanonicalRequest.js
This fixes https://github.com/scality/Arsenal/issues/151.
I will open a PR in S3 with tests tomorrow.
> Fix compat for query auth

- index.d.ts
Only implementing what we need right now.
Based on #141
> feat(typescript): add clustering definition

- lib/auth/auth.js
- tests/unit/auth/v2/errorHandling.js
- tests/unit/auth/v2/publicAccess.js
To facilitate:
https://github.com/scality/S3/pull/204
https://github.com/scality/Vault/pull/592
> Enable batch policy evaluation

- lib/policyEvaluator/evaluator.js
- lib/policyEvaluator/utils/conditions.js
- tests/unit/policyEvaluator.js
This fix allows user to make an S3request not related to the negation condition operator.
> FIX negation operator without request context

- index.js
- lib/testing/matrix.js
- tests/unit/matrix.js
Create matrix module for testing multiples configuration. Adapted for AWS S3.
@rahulreddy
> FT: Provide an matrix library for testing multiples configuration

- index.js
- lib/algos/list/delimiter.js
- lib/algos/list/delimiterMaster.js
- lib/algos/list/delimiterVersions.js
- lib/versioning/constants.js
- lib/versioning/utils.js
- tests/unit/algos/list/delimiterMaster.js
- tests/unit/algos/list/delimiterVersions.js
and extend a bit existing listing algorithm for listing latest versions.
> add versioning listing algorithm

- circle.yml
- lib/auth/v4/awsURIencode.js
- lib/policyEvaluator/utils/conditions.js
- tests/unit/auth/v4/signingKey.js
> FT: Update buffer api

- index.js
- lib/ipCheck.js
- lib/policyEvaluator/RequestContext.js
- lib/policyEvaluator/utils/conditions.js
- tests/unit/ipCheck.js
This PR includes the following commits
- refactor: move ipcheck methods for reuse
- ft: utility to check if IP matches a cidr range
> ft: utility to check if IP matches a cidr range

- lib/auth/v2/headerAuthCheck.js
- lib/auth/v2/queryAuthCheck.js
- lib/auth/v4/queryAuthCheck.js
- lib/auth/vault.js
Using `git merge --no-ff --no-commit origin/rel/1.1` with `rel/6.2` as a baseline.
> Forward porting rel/1.1 to rel/6.2

- lib/policyEvaluator/RequestContext.js
> FT: Iam policies

- lib/auth/v2/queryAuthCheck.js
> COMPAT: Increase Signature V2 Expires param

- lib/algos/list/MPU.js
- tests/unit/algos/list/MPU.js
* Related to https://github.com/scality/S3/pull/345
> BF: Fetches the correct value for `StorageClass`

- lib/auth/v2/checkRequestExpiry.js
- lib/auth/v2/headerAuthCheck.js
- tests/unit/auth/v2/checkRequestExpiry.js
> COMPAT: Date before epoch

- lib/policyEvaluator/RequestContext.js
Part of S3 Bucket Website API implementation
> FT: Add PutBucketWebsite to RequestContext map

- lib/policyEvaluator/RequestContext.js
Part of S3 deleteBucketWebsite API implementation
> FT: Add DeleteBucketWebsite to RequestContext map

- lib/policyEvaluator/RequestContext.js
Part of S3 getBucketWebsite API implementation
> FT: Add GetBucketWebsite to RequestContext map

- lib/auth/v2/getCanonicalizedResource.js
Required for S3 CORS API implementation
> FT: Add cors as canonical subresource

- errors/arsenalErrors.json
Another error needed for s3 getBucketCors API.
> FT: Add NoSuchCORSConfiguration error

- errors/arsenalErrors.json
Required for S3 CORS response.
> FT: Add AccessForbidden error

- lib/network/http/server.js
Fix error display on client error in http server
> FIX: http/server: Fix error diplay (client error)

- lib/policyEvaluator/evaluator.js
- tests/unit/policyEvaluator.js
- tests/utils/samplePolicies.json
Check with case insensitive the policy action
Fixes https://github.com/scality/Arsenal/issues/219
> FIX: Case insensitive action

- lib/auth/v4/createCanonicalRequest.js
- lib/auth/v4/headerAuthCheck.js
- lib/auth/v4/validateInputs.js
- lib/policyEvaluator/RequestContext.js
> FT: Allow ring policies

- circle.yml
- package.json
- tests/unit/stringHash.js
> FT: Node v6

- lib/auth/v4/createCanonicalRequest.js
- tests/unit/auth/v4/createCanonicalRequest.js
> FIX: Trim white space for v4 auth

- lib/versioning/VersionID.js
- tests/unit/versioning/VersionID.js
Removing encryption and switching to hex for URL-safetyness.
> rf: change encoding of version ids [S3C-184]

- errors/arsenalErrors.json
- index.d.ts
- lib/auth/v2/getCanonicalizedResource.js
- lib/policyEvaluator/RequestContext.js
BEFORE MERGING: remove the version alias in `package.json`
> FT: putObjectTagging

- lib/auth/auth.js
- lib/auth/v2/headerAuthCheck.js
- lib/auth/v2/queryAuthCheck.js
- lib/auth/v4/headerAuthCheck.js
- lib/auth/v4/queryAuthCheck.js
- lib/constants.js
- lib/policyEvaluator/RequestContext.js
- tests/unit/auth/v2/headerAuthCheck.js
- tests/unit/auth/v2/queryAuthCheck.js
- tests/unit/auth/v4/headerAuthCheck.js
This PR introduce the security token needed for
authenticate request with temporary credentials.
See https://scality.atlassian.net/browse/S3C-380
> S3C-380: Get security token

- lib/policy/userPolicySchema.json
- tests/unit/policy/test_policyValidator.js
Allowing trust policy to be evaluated
Fix https://scality.atlassian.net/browse/S3C-405
> S3C-405: Trust policy validation

- errors/arsenalErrors.json
- lib/policyEvaluator/RequestContext.js
Add getBucketReplication and new error.
> FT: Add getBucketReplication

- index.js
- lib/s3routes/routes.js
- lib/s3routes/routes/routeDELETE.js
- lib/s3routes/routes/routeGET.js
- lib/s3routes/routes/routeHEAD.js
- lib/s3routes/routes/routeOPTIONS.js
- lib/s3routes/routes/routePOST.js
- lib/s3routes/routes/routePUT.js
- lib/s3routes/routes/routeWebsite.js
- lib/s3routes/routesUtils.js
- tests/unit/s3routes/routesUtils/getBucketNameFromHost.js
- tests/unit/s3routes/routesUtils/isValidBucketName.js
- tests/unit/s3routes/routesUtils/normalizeRequest.js
Dependency of https://github.com/scality/S3/pull/768
To better reference changes from S3 code, view https://github.com/scality/Arsenal/commit/1ea0e96273183965458ffe5e67a4590ad1ab7a56 .
> Rf/extract s3routes [S3C-511]

- lib/auth/in_memory/Backend.js
- tests/unit/auth/in_memory/checkPolicies.js
Dependency of https://github.com/scality/S3/pull/779
Changes in s3 to use this module have not been merged yet since this fix was needed before regular ci tests (in-memory auth backend) would pass.
> fix: missing parameter in buildArn call

- lib/network/http/server.js
Add `checkContinue` and `checkExpectation` server events.
> FT: adding more server handlers

- index.js
- lib/storage/metadata/bucketclient/LogConsumer.js
- tests/unit/storage/metadata/bucketclient/LogConsumer.js
Use this client to fetch logs from bucketd in a way consistent between MetaData and bucketfile.
> add raft client on top of bucketclient API

- lib/storage/metadata/file/MetadataFileServer.js
Returns the deployment-specific uuid through the metadata API.
> Expose UUID through the Metadata service

- index.js
- lib/s3middleware/validateConditionalHeaders.js
- tests/unit/s3middleware/validateConditionalHeaders.js
Dep of https://github.com/scality/S3/pull/807 & https://github.com/scality/Mystique/pull/18
> ft: extract s3 conditional header validation

- index.js
- lib/constants.js
- lib/s3middleware/MD5Sum.js
- tests/unit/s3middleware/MD5Sum.js
- tests/utils/DummyRequest.js
Dependency of https://github.com/scality/Mystique/pull/33
No modifications from source code in s3.
> ft: extract MD5Sum util

- lib/auth/in_memory/validateAuthConfig.js
- lib/network/rest/RESTClient.js
- lib/network/rest/RESTServer.js
- lib/storage/data/file/DataFileStore.js
- lib/storage/metadata/bucketclient/LogConsumer.js
- lib/storage/metadata/file/MetadataFileClient.js
- lib/storage/metadata/file/MetadataFileServer.js
- tests/unit/auth/in_memory/validateAuthConfig.js
- tests/unit/network/http/server.js
- tests/unit/network/rest/index.js
> S3C-703: Update werelogs config handling design

- lib/policyEvaluator/RequestContext.js
Allow vault sso to run policy evaluator
See https://scality.atlassian.net/browse/S3C-586
> S3C-586: [policies] Allow sso scope checking

- lib/s3routes/routes.js
- lib/s3routes/routesUtils.js
Dependency of https://github.com/scality/Mystique/pull/40
Add blacklisting for object prefixes.
> ft: blacklist object prefixes

- index.js
- lib/s3middleware/azureHelpers/ResultsCollector.js
- lib/s3middleware/azureHelpers/SubStreamInterface.js
- lib/s3middleware/azureHelpers/mpuUtils.js
- lib/s3middleware/objectUtils.js
- tests/unit/s3middleware/azureHelpers/mpuUtils.js
- tests/unit/s3middleware/objectUtils.js
Pulls utils needed by Zenko for Azure putPart API from Mystique and makes them accessible in s3middleware.
> Add azure putpart utils

- lib/storage/metadata/file/MetadataFileClient.js
Needed for https://github.com/scality/backbeat/pull/37.
> FT: Return logProxy from openRecordLog

- lib/s3middleware/azureHelpers/mpuUtils.js
Moving a few more functions needed for Azure putPart from S3 to s3middleware
> ft: put putPart utils in s3middleware

- lib/auth/v4/createCanonicalRequest.js
- lib/auth/v4/validateInputs.js
- lib/policyEvaluator/RequestContext.js
- lib/policyEvaluator/evaluator.js
- lib/policyEvaluator/principal.js
- lib/policyEvaluator/utils/conditions.js
- tests/unit/policy/test_principalEvaluator.js
Check conditions for principal evaluation
Fixes https://scality.atlassian.net/browse/MD-69
> MD-69: Condition checking

- lib/s3routes/routes.js
- lib/s3routes/routes/routeGET.js
- allow OPTIONS for get service
- return corsHeaders for get service
> Allow CORS for Get Service

- index.js
- lib/models/ARN.js
- tests/unit/models/ARN.spec.js
Will be used by backbeat for roles, and potentially can be used for other components that manipulate ARNs.
> ARN object model class

- circle.yml
- index.js
- lib/metrics/RedisClient.js
- lib/metrics/StatsClient.js
- lib/s3routes/routes.js
- lib/s3routes/routesUtils.js
- package.json
- tests/unit/metrics/StatsClient.js
Moving StatsClient and RedisClient from S3 repo to reuse classes
> chore: move stats and redisclient from s3

- lib/constants.js
They are needed for backbeat echo mode.
> rf: move a couple S3 constants to Arsenal

- lib/s3middleware/azureHelpers/mpuUtils.js
Fix to handle when Azure requests throw errors instead of returning them in the callback.
Dependency of https://github.com/scality/S3/pull/934
> Fix: Wrap Azure calls with try/catch

- lib/auth/v2/queryAuthCheck.js
- lib/auth/v4/validateInputs.js
- tests/unit/auth/v4/queryAuthCheck.js
https://github.com/scality/S3/pull/1009
> S3C-885: Change v2 query auth window to 7 days

- lib/s3routes/routes.js
- lib/s3routes/routes/routeGET.js
Dependency of https://github.com/scality/S3/pull/1036
> Revert/7.2 get service cors [S3C-1009]

- lib/s3middleware/azureHelpers/mpuUtils.js
Dependency of https://github.com/scality/Mystique/pull/112 and https://github.com/scality/S3/pull/1049
> rf: avoid hacky trick to store number subparts

- lib/models/ObjectMD.js
- lib/models/ReplicationConfiguration.js
- tests/unit/models/object.js
Depends on https://github.com/scality/S3/pull/1066.
> FT: Support multiple replication storage classes

- lib/models/ObjectMD.js
- lib/models/ReplicationConfiguration.js
- tests/unit/models/object.js
> FT: Add multiple replication site version IDs

- lib/models/ReplicationConfiguration.js
Depends on: https://github.com/scality/S3/pull/1070
> FIX: Two roles when scality replication endpoint

- lib/storage/metadata/mongoclient/MongoClientInterface.js
- lib/storage/metadata/mongoclient/readStream.js
Support searchOptions for Mongo backend
> ZENKO-89 Ft/mongo search

- lib/s3routes/routesUtils.js
This reverts commit ba593850b90e6fc4dee8c01980db4a98f7944c0a.
> Revert "bf: close/end readable/response streams on errors"

- eve/main.yml
- eve/workers/master/Dockerfile
- eve/workers/master/arsenal_packages.list
- eve/workers/master/buildbot_worker_packages.list
> FWD: 7.4 Setting up EVE pipeline

- eve/main.yml
Work from tcarmet, just adding it
> ft(test): EVE-817 add pensieveCreds tests

- lib/s3routes/routesUtils.js
retrieveData rework :
Use the proven 6.4 code with an eachSeries, replacing the recursion.
Isolate Azure in a separate function.
> S3C-1026: S3 consumes too much tcp memory

- index.js
- lib/storage/metadata/MetadataWrapper.js
- lib/storage/metadata/bucketclient/BucketClientInterface.js
- lib/storage/metadata/file/BucketFileInterface.js
- lib/storage/metadata/file/MetadataFileClient.js
- lib/storage/metadata/in_memory/ListMultipartUploadsResult.js
- lib/storage/metadata/in_memory/ListResult.js
- lib/storage/metadata/in_memory/bucket_mem.js.Design.md
- lib/storage/metadata/in_memory/bucket_utilities.js
- lib/storage/metadata/in_memory/getMultipartUploadListing.js
- lib/storage/metadata/in_memory/metadata.js
- lib/storage/metadata/in_memory/metastore.js
- lib/storage/metadata/mongoclient/MongoClientInterface.js
Extract metadata backends from S3 to here so backbeat can use these features.
Merge this PR before https://github.com/scality/S3/pull/1129 and https://github.com/scality/backbeat/pull/187
JIRA ticket: https://scality.atlassian.net/browse/ZENKO-140
> Ft/move md backends from S3

- errors/arsenalErrors.json
- lib/models/LifecycleConfiguration.js
- tests/unit/models/LifecycleConfiguration.js
A few things had to be changed in the lifecycle model in order to be totally AWS compliant:
- added MissingRequiredParameter error
- don't throw error if multiple Prefixes are included, just use the last one
- fixed returned error in various situations
- fix expiration date regex
- add check for rule including both Tags and ExpiredObjectDeleteMarker (not allowed)
- tests galore!
> bf: minor lifecycle fixes

- circle.yml
- package.json
Relax node engine to version superior to the current one, to allow upgrade
> FIX: Node engine

- lib/storage/metadata/mongoclient/MongoClientInterface.js
Revert deletes from https://github.com/scality/Arsenal/pull/425
> ZENKO-222 bf: revert mongo url

- lib/storage/metadata/mongoclient/MongoClientInterface.js
Skip MPU shadow buckets when preparing a list of buckets for reporting
> Skip MPU shadow buckets

- index.js
- lib/s3middleware/validateConditionalHeaders.js
- tests/unit/s3middleware/validateConditionalHeaders.js
(cherry picked from commit 92da4c90e55b9adfbb9c9ec7864df857f5fb04b5)
> Backport: master to rel/7.4-beta

- lib/storage/metadata/mongoclient/MongoClientInterface.js
the original code had locations only count replicated data.
this fix adds count for data stored directly on the external backends
> fx: correct data managed count

- index.js
- lib/backbeat/Metrics.js
- lib/backbeat/routes.js
- lib/metrics/StatsModel.js
Let's eliminate this [TODO](https://github.com/scality/S3/blob/master/lib/utilities/reportHandler.js#L79). 🚀
> rf: S3C-1399 Add Backbeat metrics and routes

- lib/models/BucketInfo.js
- tests/unit/models/BucketInfo.js
Edit to add uid to all buckets, and remove `generateUid`
> ft: S3C-1391 add bucket uid property

- lib/storage/metadata/in_memory/bucket_utilities.js
- tests/unit/storage/metadata/in_memory/bucket_utilities.js
for in_memory only
listMultipartUpload should not list current marker in the
listing. Previously, it would include the marker as the
first item in the list
> bf: do not include current UploadIdMarker in list

- lib/algos/list/delimiter.js
- lib/storage/metadata/mongoclient/readStream.js
removed the mongo cursor hard coded limit as that introduced undesired
behavior with small max-keys
> bf: ZENKO-314 remove mongo cursor limit

- lib/auth/v4/headerAuthCheck.js
- lib/auth/v4/queryAuthCheck.js
- tests/unit/auth/v4/headerAuthCheck.js
- tests/unit/auth/v4/queryAuthCheck.js
(cherry picked from commit 160b96060747f589b8b38fa5219a7a14cd857a47)
> FX: constructing v4 query auth signature with proxyPath

- lib/backbeat/Metrics.js
- tests/unit/backbeat/Metrics.js
Fix/edit byte conversion and use accurate bytes
> bf: ZENKO-355 crr stats byte conversion
