scality/Arsenal

index.js
lib/extension/delimiter.extension.js
lib/extension/list.extension.js
lib/extension/listMPU.extension.js
lib/extension/sumSample.extension.js
package.json
tests/unit/listMpuExtension.js

S3 metadata file backend uses the same extensions than metadata to process delimiter and MPU queries.
At some point in time, Metadata would need to load extensions from here with an associative array (no need to dynamically load those files).

Move extensions to Arsenal

---

lib/auth/auth.js
lib/auth/in_memory/vaultUtilities.js
lib/auth/v2/constructStringToSign.js
lib/auth/v2/headerAuthCheck.js
lib/auth/v2/queryAuthCheck.js
lib/auth/v4/headerAuthCheck.js
lib/auth/v4/queryAuthCheck.js
tests/unit/auth/v2/errorHandling.js
tests/unit/auth/v2/publicAccess.js
tests/unit/auth/v2/signature.js
tests/unit/auth/v4/headerAuthCheck.js
tests/unit/auth/v4/queryAuthCheck.js

- Replace request.query by an object data to
pass to the function
- Allow using another service than s3 in the
signingKey
- Split the check and the backend call for the
authentification

FT: Use data && make check synchronous

---

lib/auth/auth.js
lib/auth/v4/constructStringToSign.js
lib/auth/v4/createCanonicalRequest.js
lib/auth/v4/headerAuthCheck.js
lib/auth/v4/queryAuthCheck.js

- Aws cli don't use payload to iam request, so the payload is compute with an empty string
- POST request compute the body into the payload even is the payload is missing
Should be merge with https://github.com/scality/Vault/pull/392 and https://github.com/scality/vaultclient/pull/83

Fix: Compute canonicalRequest for post request

---

lib/auth/v4/createCanonicalRequest.js

- Aws cli has a bug that convert spaces into '+' into request
body, add a check for the userAgent to fix the
payload computation

[CanonicalRequest](fix): Fix spaces from aws-cli

---

lib/auth/v4/createCanonicalRequest.js

This change is needed in the signature calculation for the go sdk to work.  Instead of adding to the "if" clause, I have removed the "if" check.  Without it, the signature works for AWS-CLI, the go sdk and the node sdk.

Handle space for all clients in post request auth

---

lib/auth/auth.js

If this function is used for a request that has a path, it won't work since the function is currently changing the path to '/'

Remove reassignment of path.

---

lib/policy/userPolicySchema.json
tests/unit/policy/test_policyValidator.js

Regex was returning partial matches, so for invalid formats string
was not failing the match.
Fix #130

BF: update regex for policy Sid

---

index.d.ts

Enable the use of the https part of arsenal for typescript users.

chore(typescript): add a small definition file

---

lib/auth/auth.js

Fixes https://github.com/scality/S3/issues/120

Pull all required headers to be signed.

---

errors/arsenalErrors.json

Actually, we return back to the client a 500 error, it's
supose to be a 404 NotFound http error.
This pull request do the changes to return the
proper error code.
- Send back 404 for AccountNotFound error
Fixes https://github.com/scality/Vault/issues/509

FIX: AccountNotFound invalid error code

---

lib/auth/v2/headerAuthCheck.js
lib/auth/v2/queryAuthCheck.js
lib/auth/v4/queryAuthCheck.js
lib/auth/vault.js

This was creating odd behaviours when importing these functionalities and the errors themselves.

fix(arsenal): remove circular dependency

---

lib/auth/v2/queryAuthCheck.js

This is a sort of forward port of https://github.com/scality/S3/pull/169
Since auth moved to arsenal after rel/1.1, the changes need to be made here and the tests added to s3 separately.
Once this is merged here and into master, we can forward port the s3 tests in scality/S3#169 from rel/1.1 into s3 rel/6.2.0-beta5 and master.

Change v2 query auth window to 1 hour 1 second

---

lib/algos/list/delimiter.js
tests/unit/algos/list/delimiter.js

Related to issue #147
Ensure that every `CommonPrefixes` entry is correctly picked up instead
of registering them as a `Contents` entry

fix(listing): handle prefixes 

---

lib/extension/delimiter.extension.js
tests/unit/extension/delimiter.js

Every commit was cherry-picked individually without any conflict whatsoever, this will ensure that we will get the fix no matter what branch ends up being used.
Related to issue #147
Ensure that every `CommonPrefixes` entry is correctly picked up instead
of registering them as a `Contents` entry

backport(fix): add listing improvements to the release branch

---

lib/auth/v2/headerAuthCheck.js
lib/auth/v2/queryAuthCheck.js
lib/auth/v4/queryAuthCheck.js

It appears that due to the order in which the require statements were running, errors was undefined in v2 header auth check and v4 query auth check.  
Fixes #156

BF: Errors not being imported

---

lib/auth/v4/createCanonicalRequest.js
tests/unit/auth/v4/createCanonicalRequest.js

Since an empty string is interpreted as false, just checking whether the header value existed was resulting in missing a signed header that had an empty string as its value.
Fixes https://github.com/scality/Arsenal/issues/163

FIX: Handle empty signed headers

---

lib/auth/auth.js
lib/auth/in_memory/backend.js
lib/auth/in_memory/vaultUtilities.js
lib/auth/v4/constructStringToSign.js
lib/auth/v4/createCanonicalRequest.js

in Node v4, default crypto encoding is binary, this
PR specify this encoding to avoid any change in the future
(node v6 in mind)

FT: Fix crypto encoding

---

lib/network/http/server.js

Werelogs is actually require by the http server
of arsenal, it should not, since its not a prod
dependencies.
This PR fix that

FIX: werelogs in dependencies of http server

---

lib/auth/v2/headerAuthCheck.js
lib/auth/v4/headerAuthCheck.js
tests/unit/auth/v4/headerAuthCheck.js

Fixes https://github.com/scality/Arsenal/issues/179
When empty/invalid/unreadable/none Date header : return AccessDenied error
**On [ceph/s3-tests](https://github.com/ceph/s3-tests), these changes fix**:
_on object with V2 auth:_
- `FAIL: s3tests.functional.test_headers.test_object_create_bad_date_empty_aws2`
- `FAIL: s3tests.functional.test_headers.test_object_create_bad_date_invalid_aws2`
- `FAIL: s3tests.functional.test_headers.test_object_create_bad_date_unreadable_aws2`
- `FAIL: s3tests.functional.test_headers.test_object_create_bad_date_none_aws2`
_on bucket with V2 auth:_
- `FAIL: s3tests.functional.test_headers.test_bucket_create_bad_date_empty_aws2`
- `FAIL: s3tests.functional.test_headers.test_bucket_create_bad_date_invalid_aws2`
- `FAIL: …

Compat: Check for invalid Date header

---

lib/auth/v2/headerAuthCheck.js
lib/auth/v4/headerAuthCheck.js
tests/unit/auth/v4/headerAuthCheck.js

Fixes #178 
When invalid Authorization header : return InvalidArgument error
AWS checks `authorization` header before `x-amz-content-sha256`
**On [ceph/s3-tests](https://github.com/ceph/s3-tests), these changes fix**:
- `FAIL: s3tests.functional.test_headers.test_object_create_bad_authorization_invalid_aws2`
- `FAIL: s3tests.functional.test_headers.test_object_create_bad_authorization_invalid_aws4`
- `FAIL: s3tests.functional.test_headers.test_bucket_create_bad_authorization_invalid_aws2`
- `FAIL: s3tests.functional.test_headers.test_bucket_create_bad_authorization_invalid_aws4`

Compat: Check for invalid Authorization header

---

lib/auth/v4/createCanonicalRequest.js
tests/unit/auth/v4/createCanonicalRequest.js

Before this change we were only taking into account
capital letters that appeared at the beginning of a query
param key.  With this change we take into account
capital letters throughout the key.
Fixes https://github.com/scality/Arsenal/issues/188

BF: Sort query params for v4 auth.

---

lib/auth/auth.js
tests/unit/auth/v2/publicAccess.js

Fixes https://github.com/scality/Arsenal/issues/182
When authorization header is incorrect: return AccessDenied error
**On [ceph/s3-tests](https://github.com/ceph/s3-tests), these changes fix**:
_bucket:_
- `FAIL: s3tests.functional.test_headers.test_bucket_create_bad_authorization_unreadable`
expect `<Code>AccessDenied</Code><Message>Anonymous access is forbidden for this operation</Message>`
_object:_
- `FAIL: s3tests.functional.test_headers.test_object_create_bad_authorization_unreadable`
expect `<Code>AccessDenied</Code><Message>Access Denied</Message>`

COMPAT: check for bad authorization header

---

lib/auth/in_memory/vaultUtilities.js

The binary digest for the signing key make
vaultclient under node v6 to generate wrong signature.
This pull request fix that.

FIX: Signing key binary

---

lib/auth/v4/headerAuthCheck.js
lib/auth/v4/queryAuthCheck.js
lib/auth/v4/validateInputs.js
tests/unit/auth/v4/headerAuthCheck.js
tests/unit/auth/v4/queryAuthCheck.js

Fixes https://github.com/scality/Arsenal/issues/180
When amz-date header is unreadable: return AccessDenied error
**On [ceph/s3-tests](https://github.com/ceph/s3-tests), these changes fix**:
Ceph test creating unreadable x-amz-date `'X-Amz-Date': '\x07'`
- `FAIL: s3tests.functional.test_headers.test_object_create_bad_amz_date_unreadable_aws4`
- `FAIL: s3tests.functional.test_headers.test_bucket_create_bad_amz_date_unreadable_aws4`
Ceph test creating  x-amz-date in past `'X-Amz-Date': '20100707T215304Z'`
- `FAIL: s3tests.functional.test_headers.test_object_create_bad_amz_date_before_today_aws4`
- `FAIL: s3tests.functional.test_headers.test_bucket_create_bad_amz_date_before_today_aws4`
Ceph test creating  x-amz-date in future `'X-Amz-Date': '20300707T215304Z'` 
- `FAIL: …

COMPAT: Check for invalid amz-date header

---

lib/algos/list/MPU.js

Currently, when using the S3 file-backend, if a `Delimiter` parameter is
defined and it does not result in a `CommonPrefixes` array that is
greater than 0, `Delimiter` is set to ''. This causes the XML response
to omit the `Delimeter` key. For compatibility with AWS, this commit
fixes the `Delimiter` response to include any `Delimiter` string given 
as a parameter or return a `Delimiter` that is `undefined`.
See the associated fix in S3: https://github.com/scality/S3/pull/435

COMPAT: Always return delimiter

---

index.js
lib/constants.js
lib/network/level-net/index.js
lib/network/level-net/sio-stream.js
lib/network/level-net/utils.js
lib/storage/metadata/file/client.js
lib/storage/metadata/file/server.js
package.json
tests/unit/network/level-net/index.js

It allows the client to do the normal levelDB operations (put, get,
delete, list keys via createReadStream) as well as creating new
sublevels. (Note that this is a purely virtual operation, nothing is
created initially but the client gets a handle to manipulate the new
sublevel).
It's built on top of socket.io which provides messaging abstraction
and helps maintaining a reliable channel (detects connection failures,
attempts to reconnect etc.). It also allows to use several namespaces
and "rooms" on the same communication channel, which may be useful
later.
There is an additional timeout for each operation, which triggers an
error after 5 seconds without an answer by default.
A custom object stream implementation has been added in order to list
keys more efficiently than the third-party …

S3C-35 New communication channel for remote sublevel

---

index.js
lib/storage/metadata/file/server.js
lib/storage/utils.js
package.json

Follow-up of https://github.com/scality/Arsenal/pull/230
Note: base branch is ft/S3C-35-metadataServer in order to see the changes on top, but this shall be merged to master.

S3C-35 init metadata storage in arsenal

---

lib/network/level-net/index.js

The rationale is that tests have failed with timeout errors, it seems 5 seconds is too short for our test VMS. 
Hopefully 30s is long enough that these errors will not occur again.

S3C-35 change metadata timeout from 5 to 30s

---

lib/algos/list/delimiterMaster.js
lib/algos/list/delimiterVersions.js
tests/unit/algos/list/delimiter.js
tests/unit/algos/list/delimiterVersions.js
tests/unit/helpers.js

This fixes a false assumption in #228 that the index of the last character of a string equaled to the length of the string https://github.com/scality/Arsenal/pull/228#discussion_r109256720.
Thanks @jonathan-gramain for pointing out this bug.

fix: wrong check of delimiter index

---

index.js
lib/constants.js
lib/jsutil.js
lib/network/http/server.js
lib/network/http/utils.js
lib/network/rest/RESTClient.js
lib/network/rest/RESTServer.js
lib/network/rest/utils.js
lib/network/rpc/level-net.js
lib/network/rpc/rpc.js
lib/network/rpc/sio-stream.js
lib/network/rpc/utils.js
lib/storage/data/file/DataFileStore.js
lib/storage/metadata/file/MetadataFileClient.js
lib/storage/metadata/file/MetadataFileServer.js
lib/storage/utils.js
tests/unit/jsutil.js
tests/unit/network/http/utils.js
tests/unit/network/rest/index.js

This is how we will be able to do the data storage in a separate
storage daemon, running on another container or host. For now a data
REST server will be spawned locally by the S3 server at startup (in S3
PR).
There are actually three parts: the REST client, the REST server, and
the DataFileStore which handles the storage logic. The DataFileStore
implementation comes from the original data/file implementation in S3
server.
The REST API uses a service base path named /DataFile, and does roughly:
- a PUT directly on /DataFile URL creates a new object file and
returns its new random hex-encoded key through its URL in a
Location response header, along with a '201 Created' response
code. The REST client extracts the key from this URL and returns it
in the callback.
- GET and DELETE on the URL …

S3C-158 REST interface for datafile backend

---

lib/auth/auth.js
lib/storage/data/file/DataFileStore.js

While adding consistency on error management, the goal is also to be able to transmit
these errors properly to the upper layers (above wrapper.js) which expect proper
arsenal errors, so that specific error types can be checked (e.g. ObjNotFound).
+ unrelated: minor fix in trace message in auth module (not worth
doing a separate PR for this one)
Linked to backbeat routes handling on S3 connector, so that data fetching routes can handle proper "not found" error types.
sproxydclient does seem to already provide Arsenal errors, so there should be nothing to do on it.

bf: use arsenal errors in data store API

---

lib/network/http/server.js

In case of error the old listeners was not removed before to restart the
server leading to some leaks and useless calls

fix(net): http server remove listeners before to rebind events

---

lib/policyEvaluator/RequestContext.js

This action maps to a standard policy action 's3:ReplicateObject', that will be
granted to backbeat on the destination.

ft: add new action type 'objectReplicate'

---

lib/s3routes/routes.js
lib/s3routes/routes/routePUT.js

Every url starting with '/_/' is now routed through a registered internal service handler in the routing code, instead of being specifically checked for a particular service. This will be useful to integrate backbeat routes properly in the next step.

cleanup: generalize internal routes handling

---

lib/versioning/VersioningRequestProcessor.js
tests/unit/versioning/VersioningRequestProcessor.js

When both 'versioning' and 'versionId' options are provided, write a
new version with the specified versionId, and also create or update
the master version like done for new versioned puts.
This is for backbeat to write new specific versions to the destination, while updating master as well
@ttvi Is it a reasonable implementation for you, or do you think it should be made another way?

ft: add a new mode in versioning put request for backbeat replication

---

lib/network/http/server.js

After we send the write continue response to the client, we should handle the request normally.

fix: continue handling req after writeContinue

---

tests/unit/stringHash.js

This as an attempt to reduce flakiness on this test, which I have seen
failing regularly due to the 10s timeout reached on the CI environment.

test: increase timeout of stringHash test

---

lib/s3routes/routesUtils.js

In addition to XML error response, JSON response will be used by
backbeat routes, because their success responses is in JSON
format. Having JSON as success and XML as error format confuses the
AWS client going to be used as the client for backbeat routes, as it
expects and can be configured for one or the other, not both.

ft: add JSON error response support

---

lib/s3routes/routesUtils.js

Before we were sending the length of the xml string before it was converted to utf-8 encoding; we should send the accurate byte length of the string when it has been utf-8 encoded in case a character conversion results in different lengths.
This issue is causing an existing functional test in Mystique to fail: we were sending a weird character by accident in an error response, and the inaccurate content-length post-encoding caused the xml to be trimmed, resulting in an XmlParserError from the sdk cilent.
If tests are desired, I might be able to add one to the s3 repo where I can make a functional test or use the node-mocks-http dependency for a unit test, or follow other suggestions.

fix: send accurate content-length for error xml

---

lib/auth/v4/createCanonicalRequest.js
tests/unit/auth/v4/createCanonicalRequest.js

If load balancer strips off expect header but
expect header was included in signed headers for v4 auth,
authentication will fail. We add back the header value here since
there is only 1 specified expect header value.

AUTH: Handle expect header stripping

---

lib/auth/v2/constructStringToSign.js
lib/s3routes/routes/routeGET.js
lib/s3routes/routes/routeWebsite.js
lib/s3routes/routesUtils.js

Dependency of https://github.com/scality/Mystique/pull/18
We used to pull them from the headers object, but they are supposed to be specified as query parameters.
It worked because of an accidental side effect with V2 auth where we assigned query parameters to request.headers. But this meant that getting the response content headers was failing with v4 auth.

bf: pull response content headers from query

---

index.js
lib/models/BucketInfo.js
lib/models/ObjectMD.js
lib/models/ReplicationConfiguration.js
lib/models/WebsiteConfiguration.js
package.json
tests/unit/models/BucketInfo.js
tests/unit/models/WebsiteConfiguration.js
tests/unit/models/object.js

This two models are needed for the S3SOFS feature into the cdmiclient
repository. The S3 one does not export modules and shared ones are in
Arsenal so move these two model modules to it.

Add Bucket and ObjecTMD models in Arsenal

---

index.js

Export DelimiterTools outside the "algorithms.list" one which contains
only delimiter classes.
Furthermore, a S3 unit test expects all the class exported in this path
to be delimiter classes and iterate on them. Instead of adding
conditional in test, give to this tool class a specific export path.

DelimiterTools export path

---

index.js
lib/network/RoundRobin.js
tests/unit/network/RoundRobin.spec.js

This is meant to be a generic round-robin manager (aka. bootstrap
list) to contact hosts in turn.
Blacklisting should be implemented in a next iteration.

ft: round-robin helper class in network/utils/RoundRobin

---

lib/models/ReplicationConfiguration.js

This commit updates the format of the expected replication config
from S3 from name/endpoint to site/servers to support the new
bootstrap list changes.

fix: update replication configuration format

---

lib/network/RoundRobin.js

Previously the shuffling may have returned the same host or at least
not go through all hosts once in turn. Fix this by not shuffling the
hosts array and by doing round-robin prior to returning the next host.

bf: force pickNextHost() to pick all hosts in turn

---

lib/s3routes/routes.js

backbeat will send this header to provide the request uid set while
processing an entry to S3 routes.

ft: log uid from sent X-Scal-Request-Uids header

---

lib/policyEvaluator/RequestContext.js

Fixing resource account id by using the target account instead of
the requester one
See https://scality.atlassian.net/browse/MD-7

MD-7: fix resource account id

---

lib/network/RoundRobin.js
tests/unit/network/RoundRobin.spec.js

When a default port is provided in constructor, set default port in
host objects returned when not provided in the bootstrap list.

ft: RoundRobin default port option

---

lib/auth/AuthInfo.js
lib/auth/in_memory/Backend.js
lib/constants.js
tests/unit/auth/AuthInfo.js

ft: service account identification support
Add support in AuthInfo for service accounts, designated by a
canonical ID starting with the service accounts namespace URL (newly
defined). We can ask if the authenticated account is a service account
or a particular one by its name.

service accounts

---

lib/models/ObjectMD.js
lib/models/ReplicationConfiguration.js
tests/unit/models/object.js

Depends on https://github.com/scality/S3/pull/922.
* Add the `storageType` field to the `replicationInfo` field of an object's metadata.
* The definition of a valid `storageClass` is expanded to include values that exist in the locationConfig.json of CloudServer.

FT: Add storageType to replicationInfo

---

lib/policyEvaluator/RequestContext.js
lib/policyEvaluator/utils/checkArnMatch.js
lib/policyEvaluator/utils/conditions.js
tests/unit/policyEvaluator.js

MD-286
There was a bug in `checkArnMatch`: it was making a ternary that is not necessary (`toLowerCase()` is done when the elements are joined).
Furthermore, it was calling this last method on an array.

ft: policy arn condition

---

index.js
lib/constants.js
lib/models/ObjectMD.js
lib/models/ObjectMDLocation.js
tests/unit/models/object.js

ObjectMD model class is now able to import metadata from stored blob
and convert it to the latest version internally.
The first use case will be for backbeat to handle metadata checks and
updates, but it should also give a cleaner way to import and
manipulate object metadata in S3.
Note: removed 'version' parameter from ObjectMD constructor since it's
handled internally by the class and should not be exposed anymore.

ft: metadata import capability in ObjectMD

---

lib/models/ReplicationConfiguration.js

Adding changes in Arsenal made in S3's `rel/7.0` branch by https://github.com/scality/S3/pull/924.

FIX: Check only defined replication rule IDs

---

lib/models/ObjectMD.js

These getters were originally in backbeat QueueEntry class, move them
to the ObjectMD model.

ft: add getters to storageClass/storageType

---

lib/auth/auth.js
lib/auth/v4/constructStringToSign.js
tests/unit/auth/v4/constructStringToSign.js

This commit adds support for sending authenticated requests to a
server through a reverse proxy. The key change is that the signature
calculated uses the path that the final server (S3/Vault) receives.

ft: support auth with proxy paths

---

lib/policyEvaluator/RequestContext.js

We currently use an action mapping with api methods, allowing the option
to send directly the action to not have to modify arsenal each new
action managed.
Need for https://scality.atlassian.net/browse/MD-292

FT: No need action mapping

---

lib/s3routes/routesUtils.js

In responseStreamData() helper, ensure the content-length is correct
with respect to data locations aggregated size. Log an error and
return internal error to the client if not.
This should catch off-by-one errors when computing ranges of data
locations to fetch and return.
Forward-port of https://github.com/scality/Arsenal/pull/365

forward-port to master of bf: sanity check on returned content-length

---

lib/s3routes/routesUtils.js

In responseStreamData() helper, ensure the content-length is correct
with respect to data locations aggregated size. Log an error and
return internal error to the client if not.
This should catch off-by-one errors when computing ranges of data
locations to fetch and return.

bf: sanity check on returned content-length

---

lib/s3middleware/azureHelpers/SubStreamInterface.js
lib/s3middleware/azureHelpers/mpuUtils.js
tests/unit/s3middleware/azureHelpers/SubStreamingInterface.js

To end streaming in case of error, we were calling an unofficial method of the stream API which was removed and does not exist in the version of node we use. The method is re-added officially in node v.8 but until we upgrade we need to destroy the streams manually, by pushing null for readables and calling stream.end() for writables.
See: https://github.com/nodejs/readable-stream/issues/124
and https://github.com/nodejs/node/pull/12925

fix: undefined stream.destroy call

---

lib/auth/auth.js

This feature will export the constructStringtoSignV2 module for use with
the Google Cloud Storage backend.

FT: Export constructStringtoSignV2 Module

---

errors/arsenalErrors.json

The feature to make the CDMI backend read only requires a dedicated
arsenal error. This new error will be thrown by all the data and
metadata callbacks which make write access.

S3C-1101 FT: add read only backend error

---

index.js
lib/s3middleware/nullStream.js
tests/unit/s3middleware/nullStream.js

This provides a new class, NullStream, that will be used to read null parts.
(null parts are parts with null keys which are generated by the NFS server when
growing a file with truncate)

ft: S3C-1065: Null part generator

---

lib/metrics/RedisClient.js
lib/metrics/StatsClient.js
tests/unit/metrics/StatsClient.js

Allow StatsClient to increment a key by a given amount, needed for https://github.com/scality/backbeat/pull/126 (to increment by byte size)
Support random order optional args case with `callback` and `amount` arg. 
I am not checking to see if the optional args passed are valid types. Instead, building on top of what exists, if a callback and/or integer are passed, they are assigned to appropriate variables for use

Ft: extend StatsClient to increase by given amount

---

lib/auth/v2/constructStringToSign.js
lib/auth/v2/getCanonicalizedAmzHeaders.js
lib/auth/v2/getCanonicalizedResource.js
tests/unit/auth/v2/canonicalization.js
tests/unit/auth/v2/constructStringToSign.js
tests/unit/auth/v2/signature.js

This feature modifies the V2 functions to handle signing Google Cloud Storage requests.
- Adds a conditional argument, clientType, to specify the headers/querystring handling method. Uses 'GCP' only when clientType === 'GCP'; the default is 'AWS'.
- Adds additional tests to accompany these changes.

FT: Modifies V2 auth functions to handle GCP

---

lib/storage/metadata/bucketclient/LogConsumer.js
package.json
tests/unit/storage/metadata/bucketclient/LogConsumer.js

Adapt LogConsumer.readRecords() to use the stream returned by the modified
BucketClient.getRaftLog() function. That allows end-to-end streaming, hence
supporting arbitrary-sized responses, which should avoid toString() exceptions
or consume excessive amounts of memory.
Goes with https://github.com/scality/bucketclient/pull/126

bf: stream response from getRaftLog()

---

circle.yml
lib/auth/v4/awsURIencode.js
lib/auth/v4/createCanonicalRequest.js
package.json
tests/unit/auth/v4/createCanonicalRequest.js

Add an exception for aws-java-sdk, which not encode the '*' character for
signatures

S3C-820: Create Policy signature does not match

---

lib/auth/v4/createCanonicalRequest.js

Fix a wrong argument, the function was expecting 'undefined' but i send 'false'

FIX: Wrong parameter encode url

---

lib/metrics/StatsClient.js

For metrics, there might be a chance byte size might be 0

fix: StatsClient zero byte increment

---

lib/models/BucketInfo.js
tests/unit/models/BucketInfo.js

Currently only setting `uid` when using `putBucketLifecycle`

ft: Add uid property to BucketInfo

---

lib/storage/metadata/mongoclient/MongoClientInterface.js

Adds total data managed information to the countItems method.
structure of data managed object:
```
{
objects: 10,
versions: 100,
buckets: 1,
bucketList: [...]
dataManaged: {
total: { curr: 1024, prev: 128 },
backend-site-1: { curr: 512, prev: 64 }
(...)
}
}
```

ft; add data managed metrics

---

lib/s3routes/routes.js

These now happen every 10s and is not informative enough to justify the volume.

Do not log report requests

---

lib/backbeat/Metrics.js
lib/metrics/StatsModel.js
package.json
tests/unit/metrics/StatsModel.js

When an interval of data in Redis expires, throughput will
abruptly reduce. Given the data we collect, we can only
calculate the average throughput. To ease the erratic
decrease on expiration of an interval, instead, get the
average of elapsed time for the newest interval and
remaining time of the interval multiplied against the
average of the just-expired interval.
In Redis, we need to save an extra interval to reference
the just-expired data.

bf: S3C-1427 use expired interval to avg out throughput

---

lib/storage/metadata/bucketclient/BucketClientInterface.js

As discussed in S3C-1412, it is necessary for S3 to interpret Bucketd health
status in order to provide more flexibility (relatively to the health check
mechanism) than failing due to a light partial unavailability of the platform.
This is done in the bucketclient backend's healthcheck method, in order to
comply with all the other backends.
Fixes S3C-1412
Signed-off-by: David Pineau <david.pineau@scality.com>

ft: interpret healthcheck status from bucketd

---

lib/backbeat/routes.js

Added new route for Prometheus client: /_/monitoring/metrics
Signed-off-by: anurag4DSB <anurag.213@gmail.com>

Zenko-21: FT: New Route for Prometheus Client

---

lib/auth/v4/headerAuthCheck.js
lib/auth/v4/queryAuthCheck.js
tests/unit/auth/v4/headerAuthCheck.js
tests/unit/auth/v4/queryAuthCheck.js

If `proxyPath` header is specified, we use it to construct our v4 query auth signature.

FX: constructing v4 query auth signature with proxyPath

---

lib/storage/metadata/mongoclient/MongoClientInterface.js

In collecting metrics for `data managed`, a `NoSuchKey` may happen, and it prevents a collection request to be skipped. This fix relaxes the error handling in the metric collection by ignoring `NoSuchKey` errors instead of returning them.

bf: ZENKO-323 relax mongo count error

---

lib/storage/metadata/mongoclient/LogConsumer.js

Don't filter internal namespace entries from mongo log, as backbeat
need the metastore entries exposed to process lifecycle entries.

bf: ZENKO-343 remove regexp-based 'ns' filtering

---

lib/backbeat/Metrics.js
lib/metrics/StatsModel.js
tests/unit/backbeat/Metrics.js
tests/unit/metrics/StatsModel.js

on a freshly started system where backbeat hasn't pushed stats yet, S3 crashes in a loop:
```"error":"Cannot read property 'map' of undefined","stack":"TypeError: Cannot read property 'map' of undefined\n at StatsModel._zip```

fix: do not crash on empty backbeat stats
